version: '3'

volumes:
  mongodb_volume: {}

services:
  db:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=IsenTP
    volumes: 
      - mongodb_volume:/data/db
  node:
    restart: always
    depends_on: 
      - db
    image: rodolpheh/hobodoth:latest
    ports:
      - 80:1234
    environment:
      - MONGODB_URI=mongodb://db:27017/IsenTP