apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: isentp
  labels:
    app: isentp
    env: dev
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: isentp
    spec:
      containers:
      - name: isentp
        image: rodolpheh/hobodoth:latest
        ports:
          - containerPort: 1234
            protocol: TCP